 
use sakila;
select count (film_id),name
from category 
inner join film_category 
using (categgory_id)
group by name 
order by count (film_id) desc;

#2 retrieve store id - need to go thropugh 4 tables 
select store_id,count(*),city,county 
from store
inner join address
using (adress_id)
inner join city 
using (country_id)
group by strore_id; 

#3 calculate total revenue generated by each store in dollars 

select store_id, sum (amount) as total_revenue
#from store staff and payment 
from store 
inner join staff
using (store_id);

###

#4 Average running time 
select name, Avg(length) as avergae_time 
from film 
inner join film category
using (film_id)
inner join category 
using (category_id)
group by name 
order by count (length) desc;

